import = [
  "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[cursor]
style =  { shape = "Block", blinking = "On" }

[window]
padding.x = 10
padding.y = 10
dimensions = { columns = 150, lines = 50 }
# opacity = 0.7
# blur = true

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 18
